### ISSUE TITLE
mimotf

### ISSUE THREAD

**Issue by fugacity59** [alchemyst/Skogestad-Python#149]
With the new mimotf object, an error occurs when a plant functions is called with a tf element only containing constants. Consider G22 in the the code below.

>>>

from utils import tf, mimotf

s = tf([1, 0])

G11 = (s - 2.5) / (s - 2)
G12 = -(0.1 * s + 1) / (s + 2)
G21 = (s - 2.5) / (0.1 * s + 1)
G22 = 1

G = mimotf([[G11, G12], [G21, G22]])
print G(0)

**Comment by alchemyst** [comment]
The problem here is located in `mimotf.__call__()`, which simply calls each of the elements in the matrix. You can fix the problem in this report by using `tf(1)` instead of `1`. This is a quick workaround, I'll check how to coerce the elements in the constructor later today.

PS: This is still not a minimal example. A minimal example would be something like

    G = mimotf([[1]])
    G(0)  

Also, try to use the Markdown support to indicate code properly.

**Comment by alchemyst** [comment]
This issue is resolved by d2109d918666980e5506107004e4a40b35f727ed. Scalar interaction should now work roughly as expected.
